1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [1]:
import numpy as np

mat = np.array([1,2,3,4,5])

if np.all(mat):
    print("None of the elements of the array is Zero")
else:
    print("Atleast one of the elements of the array is Zero")

None of the elements of the array is Zero


3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two 
   given

In [3]:
import numpy as np
mat1 = np.array([1, 2, 3, 4, 5])
mat2 = np.array([2, 4, 6, 8, 10])
print("Test whether none of the elements of mat1 is zero:")
print(np.all(mat1))
print("Element-wise comparison (equal) of mat1 and mat2:")
print(np.equal(mat1, mat2))
print("Element-wise comparison (equal within a tolerance) of mat1 and mat2:")
print(np.allclose(mat1, mat2))

Test whether none of the elements of mat1 is zero:
True
Element-wise comparison (equal) of mat1 and mat2:
[False False False False False]
Element-wise comparison (equal within a tolerance) of mat1 and mat2:
False


4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [17]:
import numpy as np
mat1=np.zeros((2,5))
print(mat1)
mat2=np.ones((5,2))
print(mat2)
#mat3=np.array([[5,5,5,5,5],[5,5,5,5,5]])
#print(mat3)
mat4=np.ones((2,5))
mat4[0 ]=5
mat4[1]=5
print(mat4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


5. Write a NumPy program to create an array of the integers from 30 to70.

In [8]:
import numpy as np
mat=np.arange(30,71)
print(mat)
print(mat.dtype)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
int32


6. Write a NumPy program to create a 3x3 identity matrix 

In [6]:
import numpy as np
mat=np.identity(3,dtype="int")
mat

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

7. Write a NumPy program to generate a random number between 0 and 1

In [8]:
import numpy as np
mat =np.random.random()
mat

0.8066251667208841

In [11]:
#Another Answer
import numpy as np
mat=np.arange(0,1)
mat

array([0])

8. Write a NumPy program to generate an array of 15 random numbers from a standard normal 
    distribution 

In [13]:
import numpy as np
mat=np.random.normal(0,1,15)
mat

array([-2.72703087, -0.42688202, -0.38366221, -0.89498537,  0.02946727,
        1.03743825, -1.65860924,  0.32764917,  0.50820411,  0.82826127,
        1.55862954, -0.53371242, -0.63113919,  3.47971469, -0.74963878])

In [22]:
#Another Answer
import numpy as np
mat=np.empty((3,5))
mat

array([[2.72703087, 0.42688202, 0.38366221, 0.89498537, 0.02946727],
       [1.03743825, 1.65860924, 0.32764917, 0.50820411, 0.82826127],
       [1.55862954, 0.53371242, 0.63113919, 3.47971469, 0.74963878]])

9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values 
    except the first and last.


In [19]:
import numpy as np
vec=np.arange(15,56)
print(vec)
print(vec[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10 

In [1]:
import numpy as np
vec=np.random.randint(0, 11, 5)
vec

array([1, 1, 4, 1, 0])

11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal 
    to 1, and inside 0.


In [30]:
import numpy as np
mat= np.ones((10,10))
mat[1:-1,1:-1]=0
print(mat)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [31]:
import numpy as np
mat=np.diag([1,2,3,4,5])
mat

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [23]:
import numpy as np
mat=np.zeros((4,4))
mat[::2,1:: 2]=1
mat[1::2, ::2]=1
print(mat)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [4]:
import numpy as np
import os
x = np.arange(10)
y = np.arange(11, 20)
print("Original arrays:")
print(x)
print(y)
np.savez('temp_arra.npz', x=x, y=y)
print("Load arrays from the 'temp_arra.npz' file:")
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


16. Write a NumPy program to extract all numbers from a given array which are less and greater than a 
    specified number

In [28]:
import numpy as np
mat=np.array([[4,45,6,4.7],[12,1.4,5,3],[18,15,25,78],[32,68,9,24]])
n=10
print (mat)
print(mat[mat>n])
print(mat[mat<n])

[[ 4.  45.   6.   4.7]
 [12.   1.4  5.   3. ]
 [18.  15.  25.  78. ]
 [32.  68.   9.  24. ]]
[45. 12. 18. 15. 25. 78. 32. 68. 24.]
[4.  6.  4.7 1.4 5.  3.  9. ]
